describe("factestio --help", function()
  it("prints a real help screen", function()
    local proc = io.popen("./bin/factestio --help 2>&1")
    assert.is_truthy(proc)

    local output = proc:read("*a")
    local ok, _, code = proc:close()

    assert.is_true(ok == true or ok == 0 or code == 0)
    assert.matches("Hierarchical scenario%-based test framework", output)
    assert.matches("Usage:%s+factestio %[%options%] %[%mod_dir%]", output)
    assert.matches("%-%-doctor", output)
    assert.matches("%-%-on", output)
    assert.matches("%-%-off", output)
    assert.matches("%-%-timeout", output)
    assert.matches("%-%-help", output)
    assert.matches("Examples:", output)
  end)
end)
