local Node = require("scenarios.factestio.src.node")

describe("Node", function()
  describe("Node.new(name, data)", function()
    it("creates node with correct name", function()
      local n = Node.new("root", { x = 1 })
      assert.equal("root", n.name)
    end)

    it("creates node with correct data", function()
      local n = Node.new("root", { x = 1 })
      assert.same({ x = 1 }, n.data)
    end)

    it("creates node with nil parent", function()
      local n = Node.new("root", {})
      assert.is_nil(n.parent)
    end)

    it("creates node with empty children table", function()
      local n = Node.new("root", {})
      assert.same({}, n.children)
    end)

    it("defaults data to empty table when not provided", function()
      local n = Node.new("root")
      assert.same({}, n.data)
    end)
  end)

  describe("Node:add(child)", function()
    it("sets child.parent to self", function()
      local parent = Node.new("parent")
      local child = Node.new("child")
      parent:add(child)
      assert.equal(parent, child.parent)
    end)

    it("appends child to self.children", function()
      local parent = Node.new("parent")
      local child = Node.new("child")
      parent:add(child)
      assert.equal(1, #parent.children)
      assert.equal(child, parent.children[1])
    end)

    it("stores multiple children in order", function()
      local parent = Node.new("parent")
      local c1 = Node.new("c1")
      local c2 = Node.new("c2")
      local c3 = Node.new("c3")
      parent:add(c1)
      parent:add(c2)
      parent:add(c3)
      assert.equal(3, #parent.children)
      assert.equal(c1, parent.children[1])
      assert.equal(c2, parent.children[2])
      assert.equal(c3, parent.children[3])
    end)
  end)

  describe("Node:walk(f)", function()
    it("calls f on root first (depth-first pre-order)", function()
      local root = Node.new("root")
      local visited = {}
      root:walk(function(n) table.insert(visited, n.name) end)
      assert.equal("root", visited[1])
    end)

    it("visits all nodes in a two-level tree", function()
      local root = Node.new("root")
      local a = Node.new("a")
      local b = Node.new("b")
      root:add(a)
      root:add(b)

      local visited = {}
      root:walk(function(n) table.insert(visited, n.name) end)
      assert.equal(3, #visited)
      assert.same({ "root", "a", "b" }, visited)
    end)

    it("visits all nodes in a three-level tree", function()
      local root = Node.new("root")
      local a = Node.new("a")
      local b = Node.new("b")
      local a1 = Node.new("a1")
      local a2 = Node.new("a2")
      root:add(a)
      root:add(b)
      a:add(a1)
      a:add(a2)

      local visited = {}
      root:walk(function(n) table.insert(visited, n.name) end)
      assert.equal(5, #visited)
      assert.same({ "root", "a", "a1", "a2", "b" }, visited)
    end)
  end)
end)
