name: CI

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: leafo/gh-actions-lua@v10
        with:
          luaVersion: "5.2"

      - uses: leafo/gh-actions-luarocks@v4

      - name: Install dependencies
        run: make deps

      - name: Lint
        run: make lint

      - name: Test
        run: make test
